name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3  # Updated from v2 to v3
        with:
          activate-environment: cb
          environment-file: environment.yml
          auto-activate-base: false

      - name: Build site
        shell: bash -l {0}
        run: |
          conda activate cb
          make build 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3  # Updated to the latest v3 version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html